# This is a basic workflow to help you get started with Actions

name: dispatch
env:
  REPO_OWNER: malikmal
  REPO_NAME: malikmal.github.io
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
on:
  repository_dispatch:
    types: [run-ping-allinone, run-pong-allinone, run-done-allinone]

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Run ${{ github.event.client_payload.command }}
        run: npm run ${{ github.event.client_payload.command }} allinone
