# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: re-build

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
        
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Cache  💾
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        uses: actions/setup-node@v1
      - run: npm install
      - run: npx next build && npx next export  # && touch out/server/pages/.nojekyll && cp -a out/server/static/. out/server/pages/_next
        env:
            CI: true
            WORDPRESS_API_URL : ${{ secrets.WORDPRESS_API_URL }}
            GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
            NODE_ENV : "production"

      # - name: change structure the file
      #   run: touch out/server/pages/.nojekyll && mkdir out/server/pages/_next && cp -rf out/static out/server/pages/_next/static && cp -rf out/data out/server/pages/_next/data

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: out # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch

